export const PAYSTACK_PAYMENT_REQUEST = "PAYSTACK_PAYMENT_REQUEST"
export const PAYSTACK_PAYMENT_SUCCESS = "PAYSTACK_PAYMENT_SUCCESS"
export const PAYSTACK_PAYMENT_FAILURE = "PAYSTACK_PAYMENT_FAILURE"

export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST"
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS"
export const VERIFY_PAYMENT_FAILURE = "VERIFY_PAYMENT_FAILURE"