export const FETCH_GUARANTOR_REQUESTS_REQUEST = "FETCH_GUARANTOR_REQUESTS_REQUEST";
export const FETCH_GUARANTOR_REQUESTS_SUCCESS = "FETCH_GUARANTOR_REQUESTS_SUCCESS";
export const FETCH_GUARANTOR_REQUESTS_FAILURE = "FETCH_GUARANTOR_REQUESTS_FAILURE";

export const ACCEPT_GUARANTOR_REQUEST_REQUEST = "ACCEPT_GUARANTOR_REQUEST_REQUEST";
export const ACCEPT_GUARANTOR_REQUEST_SUCCESS = "ACCEPT_GUARANTOR_REQUEST_SUCCESS";
export const ACCEPT_GUARANTOR_REQUEST_FAILURE = "ACCEPT_GUARANTOR_REQUEST_FAILURE";

export const DECLINE_GUARANTOR_REQUEST_REQUEST = "DECLINE_GUARANTOR_REQUEST_REQUEST";
export const DECLINE_GUARANTOR_REQUEST_SUCCESS = "DECLINE_GUARANTOR_REQUEST_SUCCESS";
export const DECLINE_GUARANTOR_REQUEST_FAILURE = "DECLINE_GUARANTOR_REQUEST_FAILURE";
