export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const USER_BY_ID_REQUEST = "USER_BY_ID_REQUEST"
export const USER_BY_ID_SUCCESS = "USER_BY_ID_SUCCESS"
export const USER_BY_ID_FAILURE = "USER_BY_ID_FAILURE"

// export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
// export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
// export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const USER_BY_PHONE_REQUEST = "USER_BY_PHONE_REQUEST";
export const USER_BY_PHONE_SUCCESS = "USER_BY_PHONE_SUCCESS";
export const USER_BY_PHONE_FAILURE = "USER_BY_PHONE_FAILURE";