export const GET_MY_NOTIFICATIONS = "GET_MY_NOTIFICATIONS";
export const GET_UNREAD_NOTIFICATIONS = "GET_UNREAD_NOTIFICATIONS";

export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ";
export const MARK_ALL_NOTIFICATIONS_AS_READ = "MARK_ALL_NOTIFICATIONS_AS_READ";

export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_ALL_NOTIFICATIONS = "DELETE_ALL_NOTIFICATIONS";

export const NOTIFICATIONS_ERROR = "NOTIFICATIONS_ERROR";
export const SET_NOTIFICATIONS_LOADING = "SET_NOTIFICATIONS_LOADING";