// Fetch all SAVINGS
export const GET_ALL_SAVINGS_REQUEST = "GET_ALL_SAVINGS_REQUEST";
export const GET_ALL_SAVINGS_SUCCESS = "GET_ALL_SAVINGS_SUCCESS";
export const GET_ALL_SAVINGS_FAILURE = "GET_ALL_SAVINGS_FAILURE";

// Fetch SAVINGS for a specific user
export const GET_USER_SAVINGS_REQUEST = "GET_USER_SAVINGS_REQUEST";
export const GET_USER_SAVINGS_SUCCESS = "GET_USER_SAVINGS_SUCCESS";
export const GET_USER_SAVINGS_FAILURE = "GET_USER_SAVINGS_FAILURE";

// NEWS SAVING
export const NEW_SAVING_REQUEST = "NEW_SAVING_REQUEST";
export const NEW_SAVING_SUCCESS = "NEW_SAVING_SUCCESS";
export const NEW_SAVING_FAILURE = "NEW_SAVING_FAILURE";

// Fetch a SAVING by ID
export const FIND_SAVING_BY_ID_REQUEST = "FIND_SAVING_BY_ID_REQUEST";
export const FIND_SAVING_BY_ID_SUCCESS = "FIND_SAVING_BY_ID_SUCCESS";
export const FIND_SAVING_BY_ID_FAILURE = "FIND_SAVING_BY_ID_FAILURE";

// Fetch SAVINGS for a specific user
export const GET_USER_LAST_SAVING_REQUEST = "GET_USER_LAST_SAVING_REQUEST";
export const GET_USER_LAST_SAVING_SUCCESS = "GET_USER_LAST_SAVING_SUCCESS";
export const GET_USER_LAST_SAVING_FAILURE = "GET_USER_LAST_SAVING_FAILURE";


