// Fetch all REPAYS
export const GET_ALL_REPAYS_REQUEST = "GET_ALL_REPAYS_REQUEST";
export const GET_ALL_REPAYS_SUCCESS = "GET_ALL_REPAYS_SUCCESS";
export const GET_ALL_REPAYS_FAILURE = "GET_ALL_REPAYS_FAILURE";

// Fetch REPAYS for a specific user
export const GET_USER_REPAYS_REQUEST = "GET_USER_REPAYS_REQUEST";
export const GET_USER_REPAYS_SUCCESS = "GET_USER_REPAYS_SUCCESS";
export const GET_USER_REPAYS_FAILURE = "GET_USER_REPAYS_FAILURE";

// NEWS REPAY
export const NEW_REPAY_REQUEST = "NEW_REPAY_REQUEST";
export const NEW_REPAY_SUCCESS = "NEW_REPAY_SUCCESS";
export const NEW_REPAY_FAILURE = "NEW_REPAY_FAILURE";

// Fetch a REPAY by ID
export const FIND_REPAY_BY_ID_REQUEST = "FIND_REPAY_BY_ID_REQUEST";
export const FIND_REPAY_BY_ID_SUCCESS = "FIND_REPAY_BY_ID_SUCCESS";
export const FIND_REPAY_BY_ID_FAILURE = "FIND_REPAY_BY_ID_FAILURE";
