// Store/Shares/actionTypes.js

export const ADD_SHARE_REQUEST = "ADD_SHARE_REQUEST";
export const ADD_SHARE_SUCCESS = "ADD_SHARE_SUCCESS";
export const ADD_SHARE_FAILURE = "ADD_SHARE_FAILURE";

export const WITHDRAW_SHARE_REQUEST = "WITHDRAW_SHARE_REQUEST";
export const WITHDRAW_SHARE_SUCCESS = "WITHDRAW_SHARE_SUCCESS";
export const WITHDRAW_SHARE_FAILURE = "WITHDRAW_SHARE_FAILURE";

export const MY_SHARES_REQUEST = "MY_SHARES_REQUEST";
export const MY_SHARES_SUCCESS = "MY_SHARES_SUCCESS";
export const MY_SHARES_FAILURE = "MY_SHARES_FAILURE";

export const ALL_SHARES_REQUEST = "ALL_SHARES_REQUEST";
export const ALL_SHARES_SUCCESS = "ALL_SHARES_SUCCESS";
export const ALL_SHARES_FAILURE = "ALL_SHARES_FAILURE";

export const APPROVE_WITHDRAW_REQUEST = "APPROVE_WITHDRAW_REQUEST";
export const APPROVE_WITHDRAW_SUCCESS = "APPROVE_WITHDRAW_SUCCESS";
export const APPROVE_WITHDRAW_FAILURE = "APPROVE_WITHDRAW_FAILURE";

export const DECLINE_WITHDRAW_REQUEST = "DECLINE_WITHDRAW_REQUEST";
export const DECLINE_WITHDRAW_SUCCESS = "DECLINE_WITHDRAW_SUCCESS";
export const DECLINE_WITHDRAW_FAILURE = "DECLINE_WITHDRAW_FAILURE";
