// Fetch all loans
export const GET_ALL_LOANS_REQUEST = "GET_ALL_LOANS_REQUEST";
export const GET_ALL_LOANS_SUCCESS = "GET_ALL_LOANS_SUCCESS";
export const GET_ALL_LOANS_FAILURE = "GET_ALL_LOANS_FAILURE";

// Fetch loans for a specific user
export const GET_MY_LOANS_REQUEST = "GET_MY_LOANS_REQUEST";
export const GET_MY_LOANS_SUCCESS = "GET_MY_LOANS_SUCCESS";
export const GET_MY_LOANS_FAILURE = "GET_MY_LOANS_FAILURE";

// Apply for a loan
export const APPLY_LOAN_REQUEST = "APPLY_LOAN_REQUEST";
export const APPLY_LOAN_SUCCESS = "APPLY_LOAN_SUCCESS";
export const APPLY_LOAN_FAILURE = "APPLY_LOAN_FAILURE";

// Approve a loan
export const APPROVE_LOAN_REQUEST = "APPROVE_LOAN_REQUEST";
export const APPROVE_LOAN_SUCCESS = "APPROVE_LOAN_SUCCESS";
export const APPROVE_LOAN_FAILURE = "APPROVE_LOAN_FAILURE";

// Reject a loan
export const REJECT_LOAN_REQUEST = "REJECT_LOAN_REQUEST";
export const REJECT_LOAN_SUCCESS = "REJECT_LOAN_SUCCESS";
export const REJECT_LOAN_FAILURE = "REJECT_LOAN_FAILURE";

// Fetch a loan by ID
export const FIND_LOAN_BY_ID_REQUEST = "FIND_LOAN_BY_ID_REQUEST";
export const FIND_LOAN_BY_ID_SUCCESS = "FIND_LOAN_BY_ID_SUCCESS";
export const FIND_LOAN_BY_ID_FAILURE = "FIND_LOAN_BY_ID_FAILURE";

