export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST";
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const FIND_USER_BY_ID_FAILURE = "FIND_USER_BY_ID_FAILURE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const ACTIVATE_USER_REQUEST = "ACTIVATE_USER_REQUEST";
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS";
export const ACTIVATE_USER_FAILURE = "ACTIVATE_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

// Savings
export const GET_USERID_SAVINGS_REQUEST = "GET_USERID_SAVINGS_REQUEST";
export const GET_USERID_SAVINGS_SUCCESS = "GET_USERID_SAVINGS_SUCCESS";
export const GET_USERID_SAVINGS_FAILURE = "GET_USERID_SAVINGS_FAILURE";

// Loans
export const GET_USERID_LOANS_REQUEST = "GET_USERID_LOANS_REQUEST";
export const GET_USERID_LOANS_SUCCESS = "GET_USERID_LOANS_SUCCESS";
export const GET_USERID_LOANS_FAILURE = "GET_USERID_LOANS_FAILURE";

// Repayments
export const GET_USERID_REPAYS_REQUEST = "GET_USERID_REPAYS_REQUEST";
export const GET_USERID_REPAYS_SUCCESS = "GET_USERID_REPAYS_SUCCESS";
export const GET_USERID_REPAYS_FAILURE = "GET_USERID_REPAYS_FAILURE";

export const USER_SHARES_REQUEST = "USER_SHARES_REQUEST";
export const USER_SHARES_SUCCESS = "USER_SHARES_SUCCESS";
export const USER_SHARES_FAILURE = "USER_SHARES_FAILURE";

// multi users
export const ADD_MULTI_USERS_REQUEST = "ADD_MULTI_USERS_REQUEST";
export const ADD_MULTI_USERS_SUCCESS = "ADD_MULTI_USERS_SUCCESS";
export const ADD_MULTI_USERS_FAILURE = "ADD_MULTI_USERS_FAILURE";

// ledger batch (ministry salary-deduction upload)
export const LEDGER_BATCH_REQUEST = "LEDGER_BATCH_REQUEST";
export const LEDGER_BATCH_SUCCESS = "LEDGER_BATCH_SUCCESS";
export const LEDGER_BATCH_FAILURE = "LEDGER_BATCH_FAILURE";

// manual saving posting (transfer receipt)
export const MANUAL_SAVING_REQUEST = "MANUAL_SAVING_REQUEST";
export const MANUAL_SAVING_SUCCESS = "MANUAL_SAVING_SUCCESS";
export const MANUAL_SAVING_FAILURE = "MANUAL_SAVING_FAILURE";

// manual repayment posting (transfer receipt)
export const MANUAL_REPAY_REQUEST = "MANUAL_REPAY_REQUEST";
export const MANUAL_REPAY_SUCCESS = "MANUAL_REPAY_SUCCESS";
export const MANUAL_REPAY_FAILURE = "MANUAL_REPAY_FAILURE";
